---
- name: Setup NMS
  hosts: all
  collections:
  - nginxinc.nginx_core
  become: yes

  vars:
    compilerver: v4.100.1

  vars_prompt:
    name: compilerver
    prompt: “Set NAP WAF Compiler Ver. v4.100.1 (default) (NAP WAF 4.1), v4.2.0 (NAP WAF 4.0), v3.1088.2 (NAP WAF 3.12.2)”
    private: no

  tasks:
  - set_fact:
      compilerver: v4.100.1
      when:
        compilerver != "v4.100.1"
        and compilerver != "v4.2.0"
        and compilerver != "v3.1088.2"

  - debug:
      msg: ‘NAP WAF Compiler Version {{ compilerver }}’

  - import_tasks: common/update-ubuntu.yaml
  - import_tasks: common/install-docker.yaml
  - import_tasks: nms/install-clickhouse.yaml
  - import_tasks: nms/install-nplus.yaml
  - import_tasks: nms/install-nms.yaml
