---
- name: Setup NMS
  hosts: all
  collections:
  - nginxinc.nginx_core
  become: yes
  tasks:
  - import_tasks: common/update-ubuntu.yaml
  - import_tasks: common/install-docker.yaml
  - import_tasks: nms/install-clickhouse.yaml
  #- import_tasks: nms/install-nplus.yaml
  - import_tasks: nms/install-nms.yaml

