---
- name: Setup NMS
  hosts: all
  collections:
  - nginxinc.nginx_core
  become: yes

  vars:
    compilerver: v4.218.0

  vars_prompt:
    name: compilerver
    prompt: “Set NAP WAF Compiler. Format:vX.X.X :(default) v4.218.0(WAF4.2), v4.100.1(WAF4.1), v4.2.0(WAF4.0), v3.1088.2(WAF3.12.2)”
    private: no

  tasks:
  - set_fact:
      compilerver: v4.218.0
      when:
        compilerver != "v4.100.1"
        and compilerver != "v4.2.0"
        and compilerver != "v3.1088.2"
        and compilerver != "v4.218.0"


  - debug:
      msg: ‘NAP WAF Compiler Version {{ compilerver }}’

  - import_tasks: common/update-ubuntu.yaml
  - import_tasks: common/install-docker.yaml
  - import_tasks: nms/install-clickhouse.yaml
  - import_tasks: nms/install-nplus.yaml
  - import_tasks: nms/install-nms.yaml
