---
- name: Create Directory for NGINX crt/key
  file:
    path: "/etc/ssl/nginx/"
    state: directory
    owner: "root"
    group: "root"
    mode: "775"

- name: Copy nginx-repo.crt
  copy:
    src: ../../nginx-repo.crt
    dest: /etc/ssl/nginx/

- name: Copy nginx-repo.key
  copy:
    src: ../../nginx-repo.key
    dest: /etc/ssl/nginx/

- name: Setup for NGINX Plus install 1
  shell: |
    sudo wget https://cs.nginx.com/static/keys/nginx_signing.key && sudo apt-key add nginx_signing.key
  args:
    chdir: ~/

- name: Setup for NGINX Plus install 2
  shell: |
    sudo wget https://cs.nginx.com/static/keys/app-protect-security-updates.key && sudo apt-key add app-protect-security-updates.key
  args:
    chdir: ~/

- name: Setup for NGINX Plus install 3
  shell: |
    sudo apt-get install -y apt-transport-https lsb-release ca-certificates wget
  args:
    chdir: ~/

- name: Setup for NGINX Plus install 4
  shell: |
    printf "deb https://pkgs.nginx.com/plus/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/nginx-plus.list
  args:
    chdir: ~/

- name: Setup for NGINX NAP WAF add repository 1
  shell: |
    printf "deb https://pkgs.nginx.com/app-protect/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/nginx-app-protect.list
  args:
    chdir: ~/

- name: Setup for NGINX NAP WAF add repository 2
  shell: |
    printf "deb https://pkgs.nginx.com/app-protect-security-updates/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee -a /etc/apt/sources.list.d/nginx-app-protect.list
  args:
    chdir: ~/

- name: Setup for NGINX NAP DoS add repository 1
  shell: |
    printf "deb https://pkgs.nginx.com/app-protect-dos/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/nginx-app-protect-dos.list
  args:
    chdir: ~/

- name: Setup for NGINX Plus install 5
  shell: |
    sudo wget -P /etc/apt/apt.conf.d https://cs.nginx.com/static/files/90pkgs-nginx
  args:
    chdir: ~/

- name: Update All Packages
  apt:
    name: "*"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    state: latest
  register: reboot_node

- name: Install nginx-plus
  apt:
    name: nginx-plus
    force_apt_get: yes
    update_cache: yes
    state: present

- name: Install app-protect
  apt:
    name: app-protect
    force_apt_get: yes
    update_cache: yes
    state: present

- name: Install app-protect-attack-signatures
  apt:
    name: app-protect-attack-signatures
    force_apt_get: yes
    update_cache: yes
    state: present

- name: Install app-protect-dos
  apt:
    name: app-protect-dos
    force_apt_get: yes
    update_cache: yes
    state: present

- name: Start service nginx, if not started
  service:
    name: nginx
    state: restarted
    
#- name: Temporary Operation for lab use
#  shell: |
#    rm /etc/apt/sources.list.d/nginx-plus.list
#    rm /etc/apt/sources.list.d/nginx-app-protect.list
#    rm /etc/apt/sources.list.d/app-protect-security-updates.list
#    rm /etc/apt/sources.list.d/nginx-app-protect-dos.list
#  args:
#    chdir: ~/

