---
- name: Install NGINX Plus
  ansible.builtin.include_role:
    name: nginx
  vars:
    nginx_type: plus
    nginx_license:
      certificate: ~/nginx-repo.crt
      key: ~/nginx-repo.key
    nginx_remove_license: false
