---
- name: Create Directory for clickhouse
  file:
    path: "/etc/clickhouse-server/"
    state: directory
    owner: "root"
    group: "root"
    mode: "775"

- name: Copy users.xml
  copy:
    src: ./users.xml
    dest: /etc/clickhouse-server/

- name: Copy config.xml
  copy:
    src: ./config.xml
    dest: /etc/clickhouse-server/

- name: Setup for clickhouse install
  shell: |
    apt-get install -y apt-transport-https ca-certificates dirmngr
  args:
    chdir: ~/

- name: Setup for clickhouse install
  shell: |
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
  args:
    chdir: ~/

- name: Setup for clickhouse install
  shell: |
    echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee /etc/apt/sources.list.d/clickhouse.list
  args:
    chdir: ~/

- name: Update All Packages
  apt:
    name: "*"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    state: latest
  register: reboot_node

- name: Install clickhouse-server
  apt:
    name: clickhouse-server
    force_apt_get: yes
    update_cache: yes
    state: present

#- name: Install clickhouse-client
#  apt:
#    name: clickhouse-client
#    force_apt_get: yes
#    update_cache: yes
#    state: present

#- name: Start service clickhouse-server, if not started
#  service:
#    name: clickhouse-server
#    state: started

